// Generated by LiveScript 1.3.1
$(document).ready(function(){
  var reload, icons, i$, to$, i, results$ = [];
  reload = function(){
    var src;
    src = this.getAttribute('data-src');
    return this.style.backgroundImage = "url(" + src + "?" + Math.random() + ")";
  };
  icons = document.querySelectorAll('.img');
  for (i$ = 0, to$ = icons.length; i$ < to$; ++i$) {
    i = i$;
    icons[i].addEventListener('mouseover', reload);
    results$.push(icons[i].addEventListener('click', reload));
  }
  return results$;
});